//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyInventoryAndBillingSystem
{
    public partial class Inventory
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Button btnAddMedicine;
        protected global::System.Web.UI.WebControls.Button btnExportExcel;
        protected global::System.Web.UI.WebControls.Button btnExportPDF;
        protected global::System.Web.UI.WebControls.GridView gvMedicines;
        protected global::System.Web.UI.WebControls.TextBox txtModalMedicineName;
        protected global::System.Web.UI.WebControls.TextBox txtModalBatchNo;
        protected global::System.Web.UI.WebControls.TextBox txtModalExpiryDate;
        protected global::System.Web.UI.WebControls.TextBox txtModalQuantity;
        protected global::System.Web.UI.WebControls.TextBox txtModalUnitPrice;
        protected global::System.Web.UI.WebControls.TextBox txtModalSellsPrice;
        protected global::System.Web.UI.WebControls.TextBox txtModalDescription;
        protected global::System.Web.UI.WebControls.Button btnSaveEdit;
        protected global::System.Web.UI.WebControls.Button btnSaveAdd;
    }
}
